version: '3.5'

services:

  database:
    container_name: dhis2-db-${INSTANCE_NAME:?INSTANCE_NAME}-${INSTANCE_TYPE:-prod}
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-dhis}
      - POSTGRES_DB=${POSTGRES_DB:-dhis}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD}
      # leave this empty
      - ENC_PASS=
    image: ${POSTGRES_IMAGE:-mdillon/postgis:10-alpine}
    labels:
      - "org.msf.description=dhis2-database"
    volumes:
      - type: volume
        source: dhis2_db_data
        target: /var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h database -U ${POSTGRES_USER} -p 5432 -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 30s
      retries: 150

  web:
    container_name: dhis2-web-${INSTANCE_NAME:?INSTANCE_NAME}-${INSTANCE_TYPE:-prod}
    image: ${DHIS2_IMAGE:-msfocbehealth/dhis2-web:2.30_alpine}
    labels:
      - "org.msf.description=dhis2-web"
    env_file:
      - .env
    volumes:
      - type: volume
        source: tomcat_log
        target: /opt/dhis2/config/logs
    environment:
      - JAVA_OPTS=${JAVA_OPTS:--XX:+UseG1GC -XX:+UseStringDeduplication -Xms512m -Xmx4096m -XX:-UseGCOverheadLimit}
      - DHIS2_HOME=/opt/dhis2/config
      - POSTGRES_USER=${POSTGRES_USER:-dhis}
      - POSTGRES_DB=${POSTGRES_DB:-dhis}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD}
      # leave this empty
      - ENC_PASS=
    ports:
      - target: 8080
        published: ${INSTANCE_PORT:-8080}
    restart: always
    depends_on:
      - database
    healthcheck:
      test: "curl -f http://web:8080"
      interval: 30s
      retries: 150

  backup:
    image: msfocbehealth/backup:latest
    labels:
      - "org.msf.description=backup"
    container_name: dhis2-bkp-${INSTANCE_NAME:?INSTANCE_NAME}-${INSTANCE_TYPE:-prod}
    env_file:
      - .env
    environment:
      - DB_BACKEND=postgres
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER:-dhis}
      - DB_HOST=database
      - DB_DB=${POSTGRES_DB:-dhis}
      - DB_PASSWORD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD}
      - ENC_TYPE=${ENC_TYPE:-7z}
      - TZ=${TZ:-Europe/Brussels}
      - ENC_PASS=${ENC_PASS:?ENC_PASS}
      - DUMP_ARGS=${DUMP_ARGS:--c -O -Fp -T aggregated* -T analytics* -T completeness*} 
    restart: always
    depends_on:
      - database
    volumes:
      - type: volume
        source: msfbackups
        target: /backups

volumes:
    dhis2_db_data:
      name: dhis2_db_${INSTANCE_NAME:?INSTANCE_NAME}_${INSTANCE_TYPE:-prod}
    tomcat_log:
      name: tomcat_log_${INSTANCE_NAME:?INSTANCE_NAME}_${INSTANCE_TYPE:-prod}
    msfbackups:
      name: dhis2_backups_${INSTANCE_NAME:?INSTANCE_NAME}_${INSTANCE_TYPE:-prod}
