version: '3.7'

services:

  web:
    networks:
      - web
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dhis2_${INSTANCE_NAME}_${INSTANCE_TYPE}.entrypoints=websecure"
      - "traefik.http.routers.dhis2_${INSTANCE_NAME}_${INSTANCE_TYPE}.rule=Host(`${FRONTEND_RULE}.ocb.msf.org`,`${FRONTEND_RULE}.msf.be`)"
      - "traefik.http.middlewares.dhis2_${INSTANCE_NAME}_${INSTANCE_TYPE}-redirect.redirectregex.regex=^https://${FRONTEND_RULE}.msf.be/(.*)"
      - "traefik.http.middlewares.dhis2_${INSTANCE_NAME}_${INSTANCE_TYPE}-redirect.redirectregex.replacement=https://${FRONTEND_RULE}.ocb.msf.org/$${1}"
      - "traefik.http.middlewares.dhis2_${INSTANCE_NAME}_${INSTANCE_TYPE}-redirect.redirectregex.permanent=true"
      - "traefik.http.routers.dhis2_${INSTANCE_NAME}_${INSTANCE_TYPE}.middlewares=dhis2_${INSTANCE_NAME}_${INSTANCE_TYPE}-redirect@docker"

networks:
  web:
    external: true

